import { NextResponse } from "next/server";
import { requireAuth, requirePermission } from "@/lib/auth";
import { db } from "@/lib/db";
import { apiError } from "@/lib/errors";
import { makeSimplePdf } from "@/lib/pdf";

export const runtime = "nodejs";

export async function GET(_: Request, ctx: { params: Promise<{ id: string }> }) {
  const auth = await requireAuth();
  if (auth.error) return auth.error;
  const deny = requirePermission(auth.user!, "FEE", "READ");
  if (deny) return deny;

  const { id } = await ctx.params;
  const paymentId = Number(id);
  if (!Number.isFinite(paymentId)) return apiError("VALIDATION_ERROR", "Invalid payment id", 400);

  const payment = await db.payment.findUnique({
    where: { id: paymentId },
    include: {
      feeType: true,
      obligation: {
        include: {
          period: true,
          household: true,
        },
      },
    },
  });

  if (!payment) return apiError("NOT_FOUND", "Payment not found", 404);

  const household = payment.obligation.household;
  const period = payment.obligation.period;
  const generatedAt = new Date().toLocaleString("vi-VN");

  const lines = [
    `Receipt no: ${payment.receiptNo}`,
    `Collected at: ${new Date(payment.paidAt).toLocaleString("vi-VN")}`,
    `Apartment: ${household.apartmentNo}`,
    `Owner: ${household.ownerName}`,
    `Fee: ${payment.feeType.name}`,
    `Period: ${period.month}/${period.year}`,
    `Amount: ${payment.paidAmount}`,
    `Method: ${payment.method}`,
    `Collector: ${payment.collectorName}`,
    `Payer: ${payment.payerName || "-"}`,
    `Payer phone: ${payment.payerPhone || "-"}`,
    `Bank tx ref: ${payment.bankTxRef || "-"}`,
    `Note: ${payment.note || "-"}`,
    `Generated by BlueMoon at ${generatedAt}`,
  ];

  const pdfBuffer = await makeSimplePdf(
    `BlueMoon Payment Receipt ${payment.receiptNo}`,
    `Generated at ${generatedAt}`,
    lines,
  );

  return new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename=payment_receipt_${payment.receiptNo}.pdf`,
    },
  });
}
